apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: levelup.azurecr.io/backend:__IMAGE_TAG__
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: "database"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "taskmanager"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres123"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devops-practice
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: devops-practice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
